modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="armorplate"
version="1.0.0"
displayName="Armor Plate Mod"
authors="_OnlyTuTu"
description='''
添加防弹插板系统，为护甲提供对TAZC以及卓越前线子弹的额外防护。
'''

[[mixins]]
config="armorplate.mixins.json"

[[dependencies.armorplate]]
modId="forge"
mandatory=true
versionRange="[47.4.10,)"
ordering="NONE"
side="BOTH"

[[dependencies.armorplate]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"