[DGH集成设置]
enableDGHIntegration = true
onlyProtectHitBodyPart = true
enableBodyPartLogging = false

[身体部位保护设置]
chestProtectsArms = true
enableHeadProtection = false
enableLegProtection = false

